FROM python:3.11-slim

# Set the working directory
WORKDIR /proyecto-patrones

# Copy the requirements file into the container
COPY requirements.txt requirements.txt 

# Install the dependencies
RUN pip install --no-cache-dir -r requirements.txt 

# Copy the rest of the application code into the container
COPY . . 

CMD ["python", "app.py"]

